# Generated by Django 3.1.2 on 2020-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=255)),
                ('post_title', models.CharField(max_length=255)),
                ('post_time', models.TimeField()),
                ('post_date', models.DateField()),
                ('post_postedby', models.CharField(max_length=255)),
                ('post_category', models.CharField(max_length=255)),
                ('post_desc', models.TextField()),
            ],
        ),
    ]
